// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210035747_NuevoEntity")]
    partial class NuevoEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.CategoriaComidaEntity", b =>
                {
                    b.Property<int>("Id_Categoria_Comida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Categoria_Comida"));

                    b.Property<int>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Id_Comida")
                        .HasColumnType("int");

                    b.HasKey("Id_Categoria_Comida");

                    b.HasIndex("Id_Categoria");

                    b.HasIndex("Id_Comida");

                    b.ToTable("Categoria_Comida", (string)null);
                });

            modelBuilder.Entity("backend.Models.CategoriaEntity", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("backend.Models.ComidaEntity", b =>
                {
                    b.Property<int>("Id_Comida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Comida"));

                    b.Property<decimal>("Azucares")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbohidratos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Fibra")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Grasas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Imagen_Url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Porcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Proteinas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id_Comida");

                    b.ToTable("Comida");
                });

            modelBuilder.Entity("backend.Models.DietaComidaEntity", b =>
                {
                    b.Property<int>("Id_Dieta_Comida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Dieta_Comida"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Id_Comida")
                        .HasColumnType("int");

                    b.Property<int>("Id_Dieta")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id_Dieta_Comida");

                    b.HasIndex("Id_Comida");

                    b.HasIndex("Id_Dieta");

                    b.ToTable("Dieta_Comida", (string)null);
                });

            modelBuilder.Entity("backend.Models.DietaEntity", b =>
                {
                    b.Property<int>("Id_Dieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Dieta"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Nutricionista")
                        .HasColumnType("int");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Dieta");

                    b.HasIndex("Id_Nutricionista");

                    b.HasIndex("Id_Paciente");

                    b.ToTable("Dieta");
                });

            modelBuilder.Entity("backend.Models.NutricionistaEntity", b =>
                {
                    b.Property<int>("Id_Nutricionista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Nutricionista"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id_Nutricionista");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Nutricionista");
                });

            modelBuilder.Entity("backend.Models.ObjetivoEntity", b =>
                {
                    b.Property<int>("Id_Objetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Objetivo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id_Objetivo");

                    b.ToTable("Objetivo", (string)null);
                });

            modelBuilder.Entity("backend.Models.PacienteEntity", b =>
                {
                    b.Property<int>("Id_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Paciente"));

                    b.Property<decimal>("Altura_Cm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Id_Nutricionista")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Objetivo")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Peso_Inicial")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id_Paciente");

                    b.HasIndex("Id_Nutricionista");

                    b.HasIndex("Id_Objetivo");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("backend.Models.PatologiaEntity", b =>
                {
                    b.Property<int>("Id_Patologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Patologia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Patologia");

                    b.ToTable("Patologia", (string)null);
                });

            modelBuilder.Entity("backend.Models.PatologiaPacienteEntity", b =>
                {
                    b.Property<int>("Id_Paciente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Patologia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Patologia_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Patologia_Paciente"));

                    b.Property<int?>("PatologiaEntityId_Patologia")
                        .HasColumnType("int");

                    b.HasKey("Id_Paciente", "Id_Patologia");

                    b.HasIndex("Id_Patologia");

                    b.HasIndex("PatologiaEntityId_Patologia");

                    b.ToTable("Patologia_Paciente", (string)null);
                });

            modelBuilder.Entity("backend.Models.PesajeEntity", b =>
                {
                    b.Property<int>("Id_Pesaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Pesaje"));

                    b.Property<DateTime>("Fecha_Pesaje")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("int");

                    b.Property<decimal?>("Masa_Muscular_Kg")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nota")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal>("Peso_Kg")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Porcentaje_Grasa")
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("Id_Pesaje");

                    b.HasIndex("Id_Paciente");

                    b.ToTable("Pesaje");
                });

            modelBuilder.Entity("backend.Models.UsuarioEntity", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Avatar_Url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("backend.Models.CategoriaComidaEntity", b =>
                {
                    b.HasOne("backend.Models.CategoriaEntity", "Categoria")
                        .WithMany()
                        .HasForeignKey("Id_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ComidaEntity", "Comida")
                        .WithMany()
                        .HasForeignKey("Id_Comida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Comida");
                });

            modelBuilder.Entity("backend.Models.DietaComidaEntity", b =>
                {
                    b.HasOne("backend.Models.ComidaEntity", "Comida")
                        .WithMany()
                        .HasForeignKey("Id_Comida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.DietaEntity", "Dieta")
                        .WithMany("DietaComidas")
                        .HasForeignKey("Id_Dieta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("backend.Models.DietaEntity", b =>
                {
                    b.HasOne("backend.Models.NutricionistaEntity", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("Id_Nutricionista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PacienteEntity", "Paciente")
                        .WithMany()
                        .HasForeignKey("Id_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutricionista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("backend.Models.NutricionistaEntity", b =>
                {
                    b.HasOne("backend.Models.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.PacienteEntity", b =>
                {
                    b.HasOne("backend.Models.NutricionistaEntity", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("Id_Nutricionista");

                    b.HasOne("backend.Models.ObjetivoEntity", "Objetivo")
                        .WithMany("Pacientes")
                        .HasForeignKey("Id_Objetivo");

                    b.HasOne("backend.Models.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutricionista");

                    b.Navigation("Objetivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.PatologiaPacienteEntity", b =>
                {
                    b.HasOne("backend.Models.PacienteEntity", "Paciente")
                        .WithMany("PatologiaPacientes")
                        .HasForeignKey("Id_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PatologiaEntity", "Patologia")
                        .WithMany()
                        .HasForeignKey("Id_Patologia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PatologiaEntity", null)
                        .WithMany("PatologiaPacientes")
                        .HasForeignKey("PatologiaEntityId_Patologia");

                    b.Navigation("Paciente");

                    b.Navigation("Patologia");
                });

            modelBuilder.Entity("backend.Models.PesajeEntity", b =>
                {
                    b.HasOne("backend.Models.PacienteEntity", "Paciente")
                        .WithMany()
                        .HasForeignKey("Id_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("backend.Models.DietaEntity", b =>
                {
                    b.Navigation("DietaComidas");
                });

            modelBuilder.Entity("backend.Models.ObjetivoEntity", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("backend.Models.PacienteEntity", b =>
                {
                    b.Navigation("PatologiaPacientes");
                });

            modelBuilder.Entity("backend.Models.PatologiaEntity", b =>
                {
                    b.Navigation("PatologiaPacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
